baseurl = "https://www.masummdar.com/"
title = "Md Abdur Razzaq Masum"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Md Abdur Razzaq Masum"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Md Abdur Razzaq Masum"
    profile = "https://www.masummdar.com/about/"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Hi, I am Masum."
    description = "Welcome to my web home. This is where I share my thoughts on code, life and  a little bit of everything. If you are interested in what I do, I  work as a web developer from my home office. When not working, I play with my  little daughter who's growing up too fast :)"

    github = "https://github.com/masummdar"
    linkedin = "https://linkedin.com/in/masummdar/"
    twitter = "https://twitter.com/masummdar"
    facebook = "https://www.facebook.com/masummdar"
    email = "masummdar@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
